[2024-07-05T13:04:21.574+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-05T13:04:21.595+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_dag.select_limit_1 scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-05T13:04:21.601+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_dag.select_limit_1 scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-05T13:04:21.602+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2024-07-05T13:04:21.612+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): select_limit_1> on 2024-07-01 00:00:00+00:00
[2024-07-05T13:04:21.617+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=128) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-05T13:04:21.619+0000] {standard_task_runner.py:63} INFO - Started process 129 to run task
[2024-07-05T13:04:21.619+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'postgres_dag', 'select_limit_1', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/postgres_dag.py', '--cfg-path', '/tmp/tmp_0e24a3n']
[2024-07-05T13:04:21.619+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask select_limit_1
[2024-07-05T13:04:21.656+0000] {task_command.py:426} INFO - Running <TaskInstance: postgres_dag.select_limit_1 scheduled__2024-07-01T00:00:00+00:00 [running]> on host ff143488b111
[2024-07-05T13:04:21.725+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Vyacheslav' AIRFLOW_CTX_DAG_ID='postgres_dag' AIRFLOW_CTX_TASK_ID='select_limit_1' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T00:00:00+00:00'
[2024-07-05T13:04:21.726+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-05T13:04:21.737+0000] {sql.py:276} INFO - Executing: SELECT * FROM source.source_data.базы_данных LIMIT 1
[2024-07-05T13:04:21.744+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-07-05T13:04:21.751+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-07-05T13:04:21.864+0000] {sql.py:487} INFO - Running statement: SELECT * FROM source.source_data.базы_данных LIMIT 1, parameters: None
[2024-07-05T13:04:21.920+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-05T13:04:21.947+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-05T13:04:21.965+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=postgres_dag, task_id=select_limit_1, run_id=scheduled__2024-07-01T00:00:00+00:00, execution_date=20240701T000000, start_date=20240705T130421, end_date=20240705T130421
[2024-07-05T13:04:21.993+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-05T13:04:22.007+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-05T13:04:22.009+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
