[2024-07-05T12:01:59.076+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-05T12:01:59.097+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_dag.select_limit_1 scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-05T12:01:59.103+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_dag.select_limit_1 scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-05T12:01:59.103+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-07-05T12:01:59.114+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): select_limit_1> on 2024-07-01 00:00:00+00:00
[2024-07-05T12:01:59.120+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1222) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-05T12:01:59.121+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'postgres_dag', 'select_limit_1', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '341', '--raw', '--subdir', 'DAGS_FOLDER/postgres_dag.py', '--cfg-path', '/tmp/tmpeatwlk59']
[2024-07-05T12:01:59.121+0000] {standard_task_runner.py:63} INFO - Started process 1223 to run task
[2024-07-05T12:01:59.122+0000] {standard_task_runner.py:91} INFO - Job 341: Subtask select_limit_1
[2024-07-05T12:01:59.158+0000] {task_command.py:426} INFO - Running <TaskInstance: postgres_dag.select_limit_1 scheduled__2024-07-01T00:00:00+00:00 [running]> on host 07d7d8ee1848
[2024-07-05T12:01:59.228+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Vyacheslav' AIRFLOW_CTX_DAG_ID='postgres_dag' AIRFLOW_CTX_TASK_ID='select_limit_1' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T00:00:00+00:00'
[2024-07-05T12:01:59.229+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-05T12:01:59.241+0000] {sql.py:276} INFO - Executing: SELECT * FROM source.source_data.базы_данных LIMIT 1
[2024-07-05T12:01:59.252+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-07-05T12:01:59.274+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-07-05T12:01:59.389+0000] {sql.py:487} INFO - Running statement: SELECT * FROM source.source_data.базы_данных LIMIT 1, parameters: None
[2024-07-05T12:01:59.445+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-05T12:01:59.473+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-05T12:01:59.492+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=postgres_dag, task_id=select_limit_1, run_id=scheduled__2024-07-01T00:00:00+00:00, execution_date=20240701T000000, start_date=20240705T120159, end_date=20240705T120159
[2024-07-05T12:01:59.536+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-05T12:01:59.549+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-05T12:01:59.551+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-05T12:59:20.250+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-05T12:59:20.271+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_dag.select_limit_1 scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-05T12:59:20.279+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_dag.select_limit_1 scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-05T12:59:20.279+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-07-05T12:59:20.291+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): select_limit_1> on 2024-07-01 00:00:00+00:00
[2024-07-05T12:59:20.296+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=59) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-05T12:59:20.298+0000] {standard_task_runner.py:63} INFO - Started process 60 to run task
[2024-07-05T12:59:20.297+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'postgres_dag', 'select_limit_1', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/postgres_dag.py', '--cfg-path', '/tmp/tmppjxa4bd6']
[2024-07-05T12:59:20.298+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask select_limit_1
[2024-07-05T12:59:20.341+0000] {task_command.py:426} INFO - Running <TaskInstance: postgres_dag.select_limit_1 scheduled__2024-07-01T00:00:00+00:00 [running]> on host ff143488b111
[2024-07-05T12:59:20.414+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Vyacheslav' AIRFLOW_CTX_DAG_ID='postgres_dag' AIRFLOW_CTX_TASK_ID='select_limit_1' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T00:00:00+00:00'
[2024-07-05T12:59:20.415+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-05T12:59:20.441+0000] {sql.py:276} INFO - Executing: SELECT * FROM source.source_data.базы_данных LIMIT 1
[2024-07-05T12:59:20.449+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-05T12:59:20.456+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    hook = self.get_db_hook()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 188, in get_db_hook
    return self._hook
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 150, in _hook
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2024-07-05T12:59:20.461+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=postgres_dag, task_id=select_limit_1, run_id=scheduled__2024-07-01T00:00:00+00:00, execution_date=20240701T000000, start_date=20240705T125920, end_date=20240705T125920
[2024-07-05T12:59:20.470+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task select_limit_1 (The conn_id `postgres_default` isn't defined; 60)
[2024-07-05T12:59:20.512+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-05T12:59:20.525+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-05T12:59:20.527+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
